name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  api-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Enable Debug Mode
        run: echo "PWDEBUG=1" >> $GITHUB_ENV
      - name: Run API tests
        run: npx playwright test --grep "@api" || (echo "Playwright test failed!" && npx playwright show-trace && exit 1)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-report
          path: playwright-report/
          retention-days: 30

  ui-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Enable Debug Mode
        run: echo "PWDEBUG=1" >> $GITHUB_ENV
      - name: Run UI tests
        run: npx playwright test --grep "@ui" || (echo "Playwright test failed!" && npx playwright show-trace && exit 1)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-report
          path: playwright-report/
          retention-days: 30
